# mypy configuration file for mdamr.

[mypy]
# Declare main path
mypy_path = src/mdnme
# Exclude the experimental folder
exclude = src/mdnme/experimental

# Ignore the following imports
# scipy
[mypy-scipy]
ignore_missing_imports = True
[mypy-scipy.sparse]
ignore_missing_imports = True
[mypy-scipy.sparse.linalg]
ignore_missing_imports = True
[mypy-scipy.spatial]
ignore_missing_imports = True
[mypy-scipy.optimize]
ignore_missing_imports = True
[mypy-scipy.spatial.qhull]
ignore_missing_imports = True

# networkx
[mypy-networkx]
ignore_missing_imports = True

# sympy
[mypy-sympy.geometry]
ignore_missing_imports = True

# meshio
[mypy-meshio]
ignore_missing_imports = True

# shapely
[mypy-shapely]
ignore_missing_imports = True
[mypy-shapely.geometry]
ignore_missing_imports = True
[mypy-shapely.speedups]
ignore_missing_imports = True

# gmsh
[mypy-gmsh]
ignore_missing_imports = True

# cython
[mypy-porepy.numerics.fv.cythoninvert]
ignore_missing_imports = True
[mypy-porepy_config]
ignore_missing_imports = True

# pymetis
[mypy-pymetis]
ignore_missing_imports = True

# numba
[mypy-numba]
ignore_missing_imports = True

# matplotlib
[mypy-matplotlib]
ignore_missing_imports = True
[mypy-matplotlib.patches]
ignore_missing_imports = True
[mypy-matplotlib.pyplot]
ignore_missing_imports = True
[mypy-matplotlib.collections]
ignore_missing_imports = True

[mypy-mpl_toolkits.mplot3d]
ignore_missing_imports = True
[mypy-mpl_toolkits.mplot3d.art3d]
ignore_missing_imports = True

# deepdiff
[mypy-deepdiff]
ignore_missing_imports = True

# porepy
[mypy-porepy]
ignore_missing_imports = True
[mypy-porepy.utils]
ignore_missing_imports = True
[mypy-porepy.utils.default_domains]
ignore_missing_imports = True
[mypy-porepy.utils.txt_io]
ignore_missing_imports = True

# quadpy
[mypy-quadpy]
ignore_missing_imports = True

# examples
[mypy-examples]
ignore_missing_imports = True
