import os
import sys
from pathlib import Path


def append_porepy_root_folder_to_path(porepy_root_folder_name: str = "porepy") -> None:
    """Append the PorePy root folder to the Python path.

    This function navigates upwards from inside the mdamr src package (when a
    file is executed) until it finds a folder named `porepy_root_folder_name`. Once
    the directory is found, the absolute path is added to the Python path.

    The primary usage of this function is to access files that are not present in the
    PorePy package (but outside). In particular, we use it to import flow models from
    the PorePy `examples` folder.

    Parameters:
        porepy_root_folder_name: str
            Name of the PorePy root folder. Default is `porepy`.

    Credits:
        This code was partially generated by ChatGPT 3.5 on the 26.02.2024. No
        license violation is intended.

    """
    # Get the path of the current module
    current_module_path = os.path.abspath(__file__)

    # Navigate to the package root by going up one level at a time
    package_root = current_module_path
    while not os.path.exists(os.path.join(package_root, porepy_root_folder_name)):
        print("Checking:", package_root)
        parent_dir = os.path.dirname(package_root)
        # Break if we reached the root directory
        if parent_dir == package_root:
            raise RuntimeError("Unable to find the package root.")
        package_root = parent_dir

    # Create PorePy path
    pp_path = Path(package_root) / Path(porepy_root_folder_name)

    # Append path to make the examples folder available
    sys.path.append(str(pp_path))
