name: Setup Conda Environment, Install Packages, and Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libglu1-mesa

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.12

    - name: Create Conda environment
      run: conda create -n estimesh python=3.12 -y

    - name: Add conda-forge channel
      run: conda config --add channels conda-forge

    - name: Create packages directory
      run: mkdir packages

    - name: Clone PorePy
      run: conda run -n estimesh --no-capture-output bash -c "cd packages && git clone https://github.com/pmgbergen/porepy.git"

    - name: Enter PorePy directory and install requirements (ignore gmsh)
      run: |
        cd packages/porepy
        grep -v 'gmsh' requirements.txt > requirements_no_gmsh.txt
        conda run -n estimesh --no-capture-output conda install --file requirements_no_gmsh.txt -y

    # On 26.08.2024, this workflow crashed due to a sqlite error. The workaround is to
    # install sqlite via conda prior to installing quadpy, porepy and mdamr
    - name: Install sqlite
      run: conda run -n estimesh --no-capture-output conda install sqlite
      
    - name: Install quadpy from conda-forge
      run: conda run -n estimesh --no-capture-output conda install -c conda-forge quadpy=0.16.10 -y

    - name: Install PorePy
      run: conda run -n estimesh --no-capture-output bash -c "cd packages/porepy && pip install ."

    - name: Install mdnme
      run: conda run -n estimesh --no-capture-output bash -c "pip install --no-deps ."

    - name: Run pytest for mdnme package
      run: conda run -n estimesh --no-capture-output bash -c "pytest tests"
